"""empty message

Revision ID: 24e3ecf3ca2d
Revises: 2734eaee18b5
Create Date: 2025-10-14 11:02:00.095806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e3ecf3ca2d'
down_revision = '2734eaee18b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('main_image_index')

    # ### end Alembic commands ###
