"""empty message

Revision ID: df892ca192d7
Revises: 24e3ecf3ca2d
Create Date: 2025-10-19 17:19:50.364687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df892ca192d7'
down_revision = '24e3ecf3ca2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_en')

    # ### end Alembic commands ###
